#!/usr/bin/env python3
"""Build the static CEL explorer data from the repository source files."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "website" / "data.js"


def build_payload() -> dict:
    taxonomy = yaml.safe_load(
        (ROOT / "taxonomies" / "disasters.yaml").read_text(encoding="utf-8")
    )
    machines = []
    for path in sorted((ROOT / "response_machines").glob("*.json")):
        machines.append(json.loads(path.read_text(encoding="utf-8")))

    return {
        "taxonomy": {
            "id": taxonomy["id"],
            "version": taxonomy["version"],
            "cel_spec": taxonomy["cel_spec"],
            "title": taxonomy["title"],
            "description": taxonomy["description"],
            "codes": taxonomy["codes"],
        },
        "machines": machines,
    }


def render(payload: dict) -> str:
    encoded = json.dumps(payload, indent=2, ensure_ascii=False)
    return (
        "/* Generated by website/build_snapshot.py. "
        "Edit taxonomies/ and response_machines/ instead. */\n"
        f"window.CEL_DATA = {encoded};\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed snapshot matches the current source files",
    )
    args = parser.parse_args()

    rendered = render(build_payload())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"{OUTPUT} is stale; run python website/build_snapshot.py")
            return 1
        print(f"{OUTPUT} is current")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
