/* Generated by website/build_snapshot.py. Edit taxonomies/ and response_machines/ instead. */
window.CEL_DATA = {
  "taxonomy": {
    "id": "cel.taxonomy.disasters",
    "version": "0.2.0",
    "cel_spec": "0.1.0",
    "title": "CEL Disaster Incident Language",
    "description": "Speakable incident words Sentinel may ingest. This tree is the CEL language, not a copy of 281 UNDRR HIP rows. Current Sentinel adapters are a subset of these words, not the ceiling. HIP / GLIDE / CAP identifiers belong in profiles so machines can interoperate without forcing crews to speak GH0101.\n",
    "codes": [
      {
        "code": "disaster",
        "label": "Disaster",
        "spoken": "disaster",
        "kind": "root",
        "description": "Root of the CEL incident language.",
        "children": [
          "disaster.fire",
          "disaster.geophysical",
          "disaster.meteorological",
          "disaster.hydrological",
          "disaster.environmental",
          "disaster.technological",
          "disaster.extraterrestrial",
          "disaster.biological"
        ]
      },
      {
        "code": "disaster.fire",
        "label": "Fire",
        "spoken": "disaster fire",
        "kind": "category",
        "parent": "disaster",
        "description": "Unwanted combustion incidents.",
        "children": [
          "disaster.fire.wildland",
          "disaster.fire.structure",
          "disaster.fire.industrial"
        ]
      },
      {
        "code": "disaster.fire.wildland",
        "label": "Wildland fire",
        "spoken": "disaster fire wildland",
        "kind": "leaf",
        "parent": "disaster.fire",
        "description": "Vegetation fire (wildfire) affecting or approaching a site.",
        "profiles": {
          "undrr_hip": "EN0205",
          "glide": "WF",
          "cap_category": "Fire"
        },
        "children": []
      },
      {
        "code": "disaster.fire.structure",
        "label": "Structure fire",
        "spoken": "disaster fire structure",
        "kind": "leaf",
        "parent": "disaster.fire",
        "description": "Fire involving a building or enclosed structure.",
        "profiles": {
          "cap_category": "Fire"
        },
        "children": []
      },
      {
        "code": "disaster.fire.industrial",
        "label": "Industrial fire",
        "spoken": "disaster fire industrial",
        "kind": "leaf",
        "parent": "disaster.fire",
        "description": "Fire at an industrial, energy, or fuel facility.",
        "profiles": {
          "cap_category": "Fire"
        },
        "children": []
      },
      {
        "code": "disaster.geophysical",
        "label": "Geophysical",
        "spoken": "disaster geophysical",
        "kind": "category",
        "parent": "disaster",
        "description": "Earth-process incidents.",
        "children": [
          "disaster.geophysical.earthquake",
          "disaster.geophysical.tsunami",
          "disaster.geophysical.volcano",
          "disaster.geophysical.landslide"
        ]
      },
      {
        "code": "disaster.geophysical.earthquake",
        "label": "Earthquake",
        "spoken": "disaster geophysical earthquake",
        "kind": "leaf",
        "parent": "disaster.geophysical",
        "description": "Seismic event.",
        "profiles": {
          "undrr_hip": "GH0101",
          "glide": "EQ",
          "cap_event": "Earthquake"
        },
        "children": []
      },
      {
        "code": "disaster.geophysical.tsunami",
        "label": "Tsunami",
        "spoken": "disaster geophysical tsunami",
        "kind": "leaf",
        "parent": "disaster.geophysical",
        "description": "Tsunami-related incident. A USGS earthquake tsunami=1 flag is a related hint, not a tsunami catalog.",
        "profiles": {
          "undrr_hip": "MH0705",
          "glide": "TS",
          "cap_event": "Tsunami"
        },
        "children": []
      },
      {
        "code": "disaster.geophysical.volcano",
        "label": "Volcano",
        "spoken": "disaster geophysical volcano",
        "kind": "leaf",
        "parent": "disaster.geophysical",
        "description": "Volcanic unrest or eruption. GDACS VO maps here.",
        "profiles": {
          "undrr_hip": "GH0201",
          "glide": "VO",
          "cap_event": "Volcano"
        },
        "children": []
      },
      {
        "code": "disaster.geophysical.landslide",
        "label": "Landslide",
        "spoken": "disaster geophysical landslide",
        "kind": "leaf",
        "parent": "disaster.geophysical",
        "description": "Gravitational mass movement, debris flow, or slope failure.",
        "profiles": {
          "undrr_hip": "GH0300"
        },
        "children": []
      },
      {
        "code": "disaster.meteorological",
        "label": "Meteorological",
        "spoken": "disaster meteorological",
        "kind": "category",
        "parent": "disaster",
        "description": "Weather incidents, including NWS CAP event classes.",
        "children": [
          "disaster.meteorological.severe_storm",
          "disaster.meteorological.tropical_cyclone",
          "disaster.meteorological.tornado",
          "disaster.meteorological.extreme_heat",
          "disaster.meteorological.extreme_cold",
          "disaster.meteorological.winter_storm",
          "disaster.meteorological.high_wind"
        ]
      },
      {
        "code": "disaster.meteorological.severe_storm",
        "label": "Severe storm",
        "spoken": "disaster meteorological severe storm",
        "kind": "leaf",
        "parent": "disaster.meteorological",
        "description": "Severe thunderstorm / convective storm.",
        "profiles": {
          "undrr_hip": "MH0103",
          "cap_event": "Severe Thunderstorm Warning"
        },
        "children": []
      },
      {
        "code": "disaster.meteorological.tropical_cyclone",
        "label": "Tropical cyclone",
        "spoken": "disaster meteorological tropical cyclone",
        "kind": "leaf",
        "parent": "disaster.meteorological",
        "description": "Tropical cyclone / hurricane / typhoon.",
        "profiles": {
          "undrr_hip": "MH0309",
          "glide": "TC",
          "cap_event": "Hurricane Warning"
        },
        "children": []
      },
      {
        "code": "disaster.meteorological.tornado",
        "label": "Tornado",
        "spoken": "disaster meteorological tornado",
        "kind": "leaf",
        "parent": "disaster.meteorological",
        "description": "Tornado.",
        "profiles": {
          "undrr_hip": "MH0305",
          "cap_event": "Tornado Warning"
        },
        "children": []
      },
      {
        "code": "disaster.meteorological.extreme_heat",
        "label": "Extreme heat",
        "spoken": "disaster meteorological extreme heat",
        "kind": "leaf",
        "parent": "disaster.meteorological",
        "description": "Heatwave / excessive heat.",
        "profiles": {
          "undrr_hip": "MH0501",
          "cap_event": "Excessive Heat Warning"
        },
        "children": []
      },
      {
        "code": "disaster.meteorological.extreme_cold",
        "label": "Extreme cold",
        "spoken": "disaster meteorological extreme cold",
        "kind": "leaf",
        "parent": "disaster.meteorological",
        "description": "Cold wave / extreme cold.",
        "profiles": {
          "undrr_hip": "MH0502",
          "cap_event": "Extreme Cold Warning"
        },
        "children": []
      },
      {
        "code": "disaster.meteorological.winter_storm",
        "label": "Winter storm",
        "spoken": "disaster meteorological winter storm",
        "kind": "leaf",
        "parent": "disaster.meteorological",
        "description": "Snow storm, blizzard, or ice storm.",
        "profiles": {
          "undrr_hip": "MH0406",
          "cap_event": "Winter Storm Warning"
        },
        "children": []
      },
      {
        "code": "disaster.meteorological.high_wind",
        "label": "High wind",
        "spoken": "disaster meteorological high wind",
        "kind": "leaf",
        "parent": "disaster.meteorological",
        "description": "Damaging non-cyclone wind.",
        "profiles": {
          "undrr_hip": "MH0301",
          "cap_event": "High Wind Warning"
        },
        "children": []
      },
      {
        "code": "disaster.hydrological",
        "label": "Hydrological",
        "spoken": "disaster hydrological",
        "kind": "category",
        "parent": "disaster",
        "description": "Water- and snow-related incidents.",
        "children": [
          "disaster.hydrological.flood",
          "disaster.hydrological.flash_flood",
          "disaster.hydrological.coastal_flood",
          "disaster.hydrological.storm_surge",
          "disaster.hydrological.drought",
          "disaster.hydrological.avalanche"
        ]
      },
      {
        "code": "disaster.hydrological.flood",
        "label": "Flood",
        "spoken": "disaster hydrological flood",
        "kind": "leaf",
        "parent": "disaster.hydrological",
        "description": "Riverine or general flooding.",
        "profiles": {
          "undrr_hip": "MH0600",
          "glide": "FL",
          "cap_event": "Flood Warning"
        },
        "children": []
      },
      {
        "code": "disaster.hydrological.flash_flood",
        "label": "Flash flood",
        "spoken": "disaster hydrological flash flood",
        "kind": "leaf",
        "parent": "disaster.hydrological",
        "description": "Rapid-onset flash flooding.",
        "profiles": {
          "undrr_hip": "MH0603",
          "cap_event": "Flash Flood Warning"
        },
        "children": []
      },
      {
        "code": "disaster.hydrological.coastal_flood",
        "label": "Coastal flood",
        "spoken": "disaster hydrological coastal flood",
        "kind": "leaf",
        "parent": "disaster.hydrological",
        "description": "Coastal flooding.",
        "profiles": {
          "undrr_hip": "MH0601",
          "cap_event": "Coastal Flood Warning"
        },
        "children": []
      },
      {
        "code": "disaster.hydrological.storm_surge",
        "label": "Storm surge",
        "spoken": "disaster hydrological storm surge",
        "kind": "leaf",
        "parent": "disaster.hydrological",
        "description": "Storm-driven coastal surge.",
        "profiles": {
          "undrr_hip": "MH0703",
          "cap_event": "Storm Surge Warning"
        },
        "children": []
      },
      {
        "code": "disaster.hydrological.drought",
        "label": "Drought",
        "spoken": "disaster hydrological drought",
        "kind": "leaf",
        "parent": "disaster.hydrological",
        "description": "Drought. GDACS DR maps here.",
        "profiles": {
          "undrr_hip": "MH0401",
          "glide": "DR"
        },
        "children": []
      },
      {
        "code": "disaster.hydrological.avalanche",
        "label": "Avalanche",
        "spoken": "disaster hydrological avalanche",
        "kind": "leaf",
        "parent": "disaster.hydrological",
        "description": "Snow avalanche.",
        "profiles": {
          "undrr_hip": "MH0801"
        },
        "children": []
      },
      {
        "code": "disaster.environmental",
        "label": "Environmental",
        "spoken": "disaster environmental",
        "kind": "category",
        "parent": "disaster",
        "description": "Environmental-quality incidents that affect sites and crews.",
        "children": [
          "disaster.environmental.smoke",
          "disaster.environmental.air_quality"
        ]
      },
      {
        "code": "disaster.environmental.smoke",
        "label": "Smoke",
        "spoken": "disaster environmental smoke",
        "kind": "leaf",
        "parent": "disaster.environmental",
        "description": "Hazardous smoke (often from wildland fire).",
        "profiles": {
          "undrr_hip": "MH0205"
        },
        "children": []
      },
      {
        "code": "disaster.environmental.air_quality",
        "label": "Air quality",
        "spoken": "disaster environmental air quality",
        "kind": "leaf",
        "parent": "disaster.environmental",
        "description": "Ambient outdoor air pollution or AQI incident.",
        "profiles": {
          "undrr_hip": "EN0103"
        },
        "children": []
      },
      {
        "code": "disaster.technological",
        "label": "Technological",
        "spoken": "disaster technological",
        "kind": "category",
        "parent": "disaster",
        "description": "Human-made infrastructure and industrial failures.",
        "children": [
          "disaster.technological.dam_failure",
          "disaster.technological.hazmat",
          "disaster.technological.explosion",
          "disaster.technological.nuclear"
        ]
      },
      {
        "code": "disaster.technological.dam_failure",
        "label": "Dam failure",
        "spoken": "disaster technological dam failure",
        "kind": "leaf",
        "parent": "disaster.technological",
        "description": "Dam or levee failure.",
        "profiles": {
          "undrr_hip": "TL0205"
        },
        "children": []
      },
      {
        "code": "disaster.technological.hazmat",
        "label": "Hazmat",
        "spoken": "disaster technological hazmat",
        "kind": "leaf",
        "parent": "disaster.technological",
        "description": "Hazardous materials release.",
        "profiles": {
          "cap_category": "CBRNE"
        },
        "children": []
      },
      {
        "code": "disaster.technological.explosion",
        "label": "Explosion",
        "spoken": "disaster technological explosion",
        "kind": "leaf",
        "parent": "disaster.technological",
        "description": "Industrial or accidental explosion.",
        "profiles": {
          "undrr_hip": "TL0304"
        },
        "children": []
      },
      {
        "code": "disaster.technological.nuclear",
        "label": "Nuclear",
        "spoken": "disaster technological nuclear",
        "kind": "leaf",
        "parent": "disaster.technological",
        "description": "Nuclear plant failure or radiological release.",
        "profiles": {
          "undrr_hip": "TL0208"
        },
        "children": []
      },
      {
        "code": "disaster.extraterrestrial",
        "label": "Extraterrestrial",
        "spoken": "disaster extraterrestrial",
        "kind": "category",
        "parent": "disaster",
        "description": "Space-weather and related incidents that affect grid and radio.",
        "children": [
          "disaster.extraterrestrial.space_weather"
        ]
      },
      {
        "code": "disaster.extraterrestrial.space_weather",
        "label": "Space weather",
        "spoken": "disaster extraterrestrial space weather",
        "kind": "leaf",
        "parent": "disaster.extraterrestrial",
        "description": "Geomagnetic storm / solar event affecting grid, GNSS, or HF radio.",
        "profiles": {
          "undrr_hip": "ET0101"
        },
        "children": []
      },
      {
        "code": "disaster.biological",
        "label": "Biological",
        "spoken": "disaster biological",
        "kind": "category",
        "parent": "disaster",
        "description": "Disease incidents. One speakable leaf, not a copy of the HIP disease catalog.",
        "children": [
          "disaster.biological.disease_outbreak"
        ]
      },
      {
        "code": "disaster.biological.disease_outbreak",
        "label": "Disease outbreak",
        "spoken": "disaster biological disease outbreak",
        "kind": "leaf",
        "parent": "disaster.biological",
        "description": "Infectious-disease outbreak of public-health concern.",
        "profiles": {
          "undrr_hip": "BI0101"
        },
        "children": []
      }
    ]
  },
  "machines": [
    {
      "id": "cel.response.earthquake_proximity",
      "version": "0.1.0",
      "cel_spec": "0.1.0",
      "title": "Earthquake proximity response machine",
      "description": "Allowed emergency response states for a site near a significant earthquake. CEL names speakable states and transitions. Consumer policy (for example VITO) decides when a named event fires. This machine is not an OIDF commissioning SAT, not a CAP alert, and carries no evidence gates.",
      "incident_types": [
        "disaster.geophysical.earthquake"
      ],
      "subject_kind": "site",
      "initial_state": "response.monitor",
      "states": [
        {
          "id": "response.monitor",
          "label": "Monitor",
          "spoken": "response monitor",
          "description": "Watch the incident. No extra site posture is implied."
        },
        {
          "id": "response.escalate",
          "label": "Escalate",
          "spoken": "response escalate",
          "description": "Elevated attention. Notify or review per consumer policy."
        },
        {
          "id": "response.isolate_load",
          "label": "Isolate load",
          "spoken": "response isolate load",
          "description": "Non-life-safety load isolation is an allowed posture. CEL does not trip breakers."
        },
        {
          "id": "response.shelter",
          "label": "Shelter",
          "spoken": "response shelter",
          "description": "Life-safety / shelter posture. CEL does not issue the directive."
        },
        {
          "id": "response.recover",
          "label": "Recover",
          "spoken": "response recover",
          "description": "Hazard receding. Return path toward monitor."
        }
      ],
      "transitions": [
        {
          "id": "detect_proximity",
          "event": "earthquake.proximity_detected",
          "from": "response.monitor",
          "to": "response.escalate",
          "description": "Earthquake is near enough that consumer policy raises attention."
        },
        {
          "id": "clear_proximity",
          "event": "earthquake.proximity_cleared",
          "from": "response.escalate",
          "to": "response.monitor",
          "description": "Proximity no longer meets the consumer watch threshold."
        },
        {
          "id": "isolate_noncritical_load",
          "event": "earthquake.isolate_load_authorized",
          "from": "response.escalate",
          "to": "response.isolate_load",
          "description": "Policy authorizes isolating non-life-safety load. Thresholds live in the consumer."
        },
        {
          "id": "restore_load_watch",
          "event": "earthquake.load_restored_watch",
          "from": "response.isolate_load",
          "to": "response.escalate",
          "description": "Load isolation lifted while the incident remains in watch."
        },
        {
          "id": "shelter_from_escalate",
          "event": "earthquake.life_safety_shelter",
          "from": "response.escalate",
          "to": "response.shelter",
          "description": "Life-safety shelter posture from elevated watch."
        },
        {
          "id": "shelter_from_isolate",
          "event": "earthquake.life_safety_shelter",
          "from": "response.isolate_load",
          "to": "response.shelter",
          "description": "Life-safety shelter posture from load-isolated posture."
        },
        {
          "id": "recover_from_escalate",
          "event": "earthquake.hazard_receding",
          "from": "response.escalate",
          "to": "response.recover",
          "description": "Incident receding from elevated watch."
        },
        {
          "id": "recover_from_isolate",
          "event": "earthquake.hazard_receding",
          "from": "response.isolate_load",
          "to": "response.recover",
          "description": "Incident receding from load-isolated posture."
        },
        {
          "id": "recover_from_shelter",
          "event": "earthquake.hazard_receding",
          "from": "response.shelter",
          "to": "response.recover",
          "description": "Incident receding from shelter posture."
        },
        {
          "id": "resume_monitor",
          "event": "earthquake.return_to_watch",
          "from": "response.recover",
          "to": "response.monitor",
          "description": "Return to routine monitoring after recovery."
        }
      ]
    },
    {
      "id": "cel.response.flood_proximity",
      "version": "0.1.0",
      "cel_spec": "0.1.0",
      "title": "Flood proximity response machine",
      "description": "Allowed emergency response states for a site near flooding. CEL names speakable states and transitions. Consumer policy (for example VITO) decides when a named event fires. This machine is not an OIDF commissioning SAT, not a CAP alert, and carries no evidence gates.",
      "incident_types": [
        "disaster.hydrological.flood",
        "disaster.hydrological.flash_flood"
      ],
      "subject_kind": "site",
      "initial_state": "response.monitor",
      "states": [
        {
          "id": "response.monitor",
          "label": "Monitor",
          "spoken": "response monitor",
          "description": "Watch the incident. No extra site posture is implied."
        },
        {
          "id": "response.escalate",
          "label": "Escalate",
          "spoken": "response escalate",
          "description": "Elevated attention. Notify or review per consumer policy."
        },
        {
          "id": "response.isolate_load",
          "label": "Isolate load",
          "spoken": "response isolate load",
          "description": "Non-life-safety load isolation is an allowed posture. CEL does not trip breakers."
        },
        {
          "id": "response.shelter",
          "label": "Shelter",
          "spoken": "response shelter",
          "description": "Life-safety / shelter posture. CEL does not issue the directive."
        },
        {
          "id": "response.recover",
          "label": "Recover",
          "spoken": "response recover",
          "description": "Hazard receding. Return path toward monitor."
        }
      ],
      "transitions": [
        {
          "id": "detect_proximity",
          "event": "flood.proximity_detected",
          "from": "response.monitor",
          "to": "response.escalate",
          "description": "Flood threat is near enough that consumer policy raises attention."
        },
        {
          "id": "clear_proximity",
          "event": "flood.proximity_cleared",
          "from": "response.escalate",
          "to": "response.monitor",
          "description": "Proximity no longer meets the consumer watch threshold."
        },
        {
          "id": "isolate_noncritical_load",
          "event": "flood.isolate_load_authorized",
          "from": "response.escalate",
          "to": "response.isolate_load",
          "description": "Policy authorizes isolating non-life-safety load. Thresholds live in the consumer."
        },
        {
          "id": "restore_load_watch",
          "event": "flood.load_restored_watch",
          "from": "response.isolate_load",
          "to": "response.escalate",
          "description": "Load isolation lifted while the incident remains in watch."
        },
        {
          "id": "shelter_from_escalate",
          "event": "flood.life_safety_shelter",
          "from": "response.escalate",
          "to": "response.shelter",
          "description": "Life-safety shelter posture from elevated watch."
        },
        {
          "id": "shelter_from_isolate",
          "event": "flood.life_safety_shelter",
          "from": "response.isolate_load",
          "to": "response.shelter",
          "description": "Life-safety shelter posture from load-isolated posture."
        },
        {
          "id": "recover_from_escalate",
          "event": "flood.hazard_receding",
          "from": "response.escalate",
          "to": "response.recover",
          "description": "Incident receding from elevated watch."
        },
        {
          "id": "recover_from_isolate",
          "event": "flood.hazard_receding",
          "from": "response.isolate_load",
          "to": "response.recover",
          "description": "Incident receding from load-isolated posture."
        },
        {
          "id": "recover_from_shelter",
          "event": "flood.hazard_receding",
          "from": "response.shelter",
          "to": "response.recover",
          "description": "Incident receding from shelter posture."
        },
        {
          "id": "resume_monitor",
          "event": "flood.return_to_watch",
          "from": "response.recover",
          "to": "response.monitor",
          "description": "Return to routine monitoring after recovery."
        }
      ]
    },
    {
      "id": "cel.response.wildland_proximity",
      "version": "0.1.0",
      "cel_spec": "0.1.0",
      "title": "Wildland fire proximity response machine",
      "description": "Allowed emergency response states for a site near a wildland fire. CEL names speakable states and transitions. Consumer policy (for example VITO) decides when a named event fires. This machine is not an OIDF commissioning SAT, not a CAP alert, and carries no evidence gates.",
      "incident_types": [
        "disaster.fire.wildland"
      ],
      "subject_kind": "site",
      "initial_state": "response.monitor",
      "states": [
        {
          "id": "response.monitor",
          "label": "Monitor",
          "spoken": "response monitor",
          "description": "Watch the incident. No extra site posture is implied."
        },
        {
          "id": "response.escalate",
          "label": "Escalate",
          "spoken": "response escalate",
          "description": "Elevated attention. Notify or review per consumer policy."
        },
        {
          "id": "response.isolate_load",
          "label": "Isolate load",
          "spoken": "response isolate load",
          "description": "Non-life-safety load isolation is an allowed posture. CEL does not trip breakers."
        },
        {
          "id": "response.shelter",
          "label": "Shelter",
          "spoken": "response shelter",
          "description": "Life-safety / shelter posture. CEL does not issue the directive."
        },
        {
          "id": "response.recover",
          "label": "Recover",
          "spoken": "response recover",
          "description": "Hazard receding. Return path toward monitor."
        }
      ],
      "transitions": [
        {
          "id": "detect_proximity",
          "event": "wildland.proximity_detected",
          "from": "response.monitor",
          "to": "response.escalate",
          "description": "Wildland fire is near enough that consumer policy raises attention."
        },
        {
          "id": "clear_proximity",
          "event": "wildland.proximity_cleared",
          "from": "response.escalate",
          "to": "response.monitor",
          "description": "Proximity no longer meets the consumer watch threshold."
        },
        {
          "id": "isolate_noncritical_load",
          "event": "wildland.isolate_load_authorized",
          "from": "response.escalate",
          "to": "response.isolate_load",
          "description": "Policy authorizes isolating non-life-safety load. Thresholds live in the consumer."
        },
        {
          "id": "restore_load_watch",
          "event": "wildland.load_restored_watch",
          "from": "response.isolate_load",
          "to": "response.escalate",
          "description": "Load isolation lifted while the incident remains in watch."
        },
        {
          "id": "shelter_from_escalate",
          "event": "wildland.life_safety_shelter",
          "from": "response.escalate",
          "to": "response.shelter",
          "description": "Life-safety shelter posture from elevated watch."
        },
        {
          "id": "shelter_from_isolate",
          "event": "wildland.life_safety_shelter",
          "from": "response.isolate_load",
          "to": "response.shelter",
          "description": "Life-safety shelter posture from load-isolated posture."
        },
        {
          "id": "recover_from_escalate",
          "event": "wildland.hazard_receding",
          "from": "response.escalate",
          "to": "response.recover",
          "description": "Incident receding from elevated watch."
        },
        {
          "id": "recover_from_isolate",
          "event": "wildland.hazard_receding",
          "from": "response.isolate_load",
          "to": "response.recover",
          "description": "Incident receding from load-isolated posture."
        },
        {
          "id": "recover_from_shelter",
          "event": "wildland.hazard_receding",
          "from": "response.shelter",
          "to": "response.recover",
          "description": "Incident receding from shelter posture."
        },
        {
          "id": "resume_monitor",
          "event": "wildland.return_to_watch",
          "from": "response.recover",
          "to": "response.monitor",
          "description": "Return to routine monitoring after recovery."
        }
      ]
    }
  ]
};
