#!/usr/bin/env python3
"""Generate the published CEL schema index and identifier manifest.

Pages serves no directory listing, so https://tylereno.me/cel/schemas/ would be
a 404 even though every identifier under it resolves. This writes the browsable
index and the machine-readable manifest from the same scan as
tooling/verify_pages_ids.py, so the index cannot advertise a path the gate does
not check.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from verify_pages_ids import BASE, ROOT, SCHEMA_DIR, served_path  # noqa: E402

# Language corpus published next to the schemas, listed on the generated index
# so the whole served surface is reachable (Pages has no directory listing).
CORPUS_DIRS = ("taxonomies", "response_machines", "crosswalks", "feeds", "normative")


def collect() -> list[tuple[str, str]]:
    """(url, source path) for every $id-declaring schema, in tree order."""
    rows: list[tuple[str, str]] = []
    for path in sorted(SCHEMA_DIR.rglob("*.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        schema_id = document.get("$id")
        if not schema_id:
            continue
        rows.append((str(schema_id), path.relative_to(ROOT).as_posix()))
    return rows


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CEL v0 — published schemas</title>
<style>
  :root {{ color-scheme: dark light; }}
  body {{ font: 16px/1.55 ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif;
         margin: 0 auto; max-width: 60rem; padding: 2.5rem 1.25rem 4rem; }}
  h1 {{ font-size: 1.6rem; margin: 0 0 .25rem; }}
  h2 {{ font-size: 1.1rem; margin: 2.5rem 0 .25rem; }}
  p {{ margin: .5rem 0 1.25rem; }}
  code {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .92em; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ text-align: left; padding: .5rem .6rem; border-bottom: 1px solid #8883; vertical-align: top; }}
  th {{ font-size: .8rem; text-transform: uppercase; letter-spacing: .04em; opacity: .7; }}
  .src {{ opacity: .65; font-size: .85em; }}
  footer {{ margin-top: 2rem; font-size: .85rem; opacity: .7; }}
</style>
</head>
<body>
<h1>CEL v0 — published schemas</h1>
<p>{count} JSON Schema documents, each self-identifying at the address below.
Canonical identifier base: <code>{base}</code>.
Machine-readable index: <a href="manifest.json">manifest.json</a>.</p>
<table>
<thead><tr><th>$id (dereferenceable)</th><th>Source path</th></tr></thead>
<tbody>
{rows}
</tbody>
</table>
<h2>Published corpus</h2>
<p>{corpus_count} vocabulary, crosswalk, feed, and response-machine files served
alongside the schemas.</p>
<table>
<thead><tr><th>File</th><th>Size</th></tr></thead>
<tbody>
{corpus}
</tbody>
</table>
<footer>Generated by <code>tooling/gen_schema_index.py</code> from the repository tree.
Do not edit by hand. Format surface: <a href="../">CEL</a>.</footer>
</body>
</html>
"""


def corpus_rows(artifact: Path) -> list[tuple[str, str]]:
    """(served path, size) for the language corpus shipped with the schemas."""
    rows: list[tuple[str, str]] = []
    for name in CORPUS_DIRS:
        base = artifact / name
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if path.is_file():
                rel = path.relative_to(artifact).as_posix()
                rows.append((rel, f"{path.stat().st_size:,} bytes"))
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="path to write index.html")
    parser.add_argument(
        "--artifact",
        default=None,
        help="served artifact root to list the corpus from (default: the parent of --out)",
    )
    args = parser.parse_args()

    rows = collect()
    if not rows:
        print("no $id-declaring schemas found", file=sys.stderr)
        return 2

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    body = "\n".join(
        f'<tr><td><a href="{html.escape(schema_id)}"><code>{html.escape(schema_id)}</code></a></td>'
        f'<td class="src"><code>{html.escape(source)}</code></td></tr>'
        for schema_id, source in rows
    )

    # The corpus is listed from the staged artifact, not the repository, so the
    # page can only advertise files that are actually served.
    artifact = Path(args.artifact).resolve() if args.artifact else out.parent.resolve().parent
    corpus = corpus_rows(artifact)
    corpus_body = "\n".join(
        f'<tr><td><a href="../{html.escape(rel)}"><code>{html.escape(rel)}</code></a></td>'
        f'<td class="src">{html.escape(size)}</td></tr>'
        for rel, size in corpus
    )

    out.write_text(
        PAGE.format(
            count=len(rows),
            base=BASE,
            rows=body,
            corpus_count=len(corpus),
            corpus=corpus_body,
        ),
        encoding="utf-8",
    )

    manifest = {
        "format": "CEL",
        "spec": "0.1.0",
        "authority": BASE,
        "schema_count": len(rows),
        "schemas": [{"url": schema_id, "source_path": source} for schema_id, source in rows],
    }
    manifest_path = out.parent / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {out} ({out.stat().st_size} bytes), {len(rows)} identifier(s)")
    print(f"wrote {manifest_path} ({manifest_path.stat().st_size} bytes)")
    for schema_id, source in rows:
        print(f"  {schema_id}  <-  {source}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
